[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Endpoints de la API
[[redirects]]
  from = "/api/save"
  to   = "/.netlify/functions/proposals-save"
  status = 200

[[redirects]]
  from = "/api/get"
  to   = "/.netlify/functions/proposals-get"
  status = 200

[[redirects]]
  from = "/api/list"
  to   = "/.netlify/functions/proposals-list"
  status = 200
